// <auto-generated />
using System;
using FolderTree.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolderTree.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230702053838_ChangeParentFolderToNullable")]
    partial class ChangeParentFolderToNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("FolderTree.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParrentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParrentId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("FolderTree.Models.Folder", b =>
                {
                    b.HasOne("FolderTree.Models.Folder", "ParrentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParrentId");

                    b.Navigation("ParrentFolder");
                });

            modelBuilder.Entity("FolderTree.Models.Folder", b =>
                {
                    b.Navigation("SubFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
